### ISSUE TITLE
Integration with Navi

### ISSUE THREAD

**Issue by ngirard** [DanCardin/sauce#30]
[Navi](https://github.com/denisidoro/navi) shines for sharing interactive or semi-interactive commands between people/projects.
I think it would pair nicely with Sauce, especially with it's cascading loading capabilities.

What I have in mind is the ability to add
```sh
sauce cheat new
sauce cheat edit
```

`cheat new` would associate a new cheat file to the current directory, and `cheat edit` would edit the cheat file using `$EDITOR`.

Finally, `sauce` would make the cheat files available to Navi, in a "cascade" way i.e. by adding the cheat files from parents directories, then the one from the current directory.

**Comment by DanCardin** [comment]
I'm probably less inclined to add a navi-specific subcommand, because per the navi docs itself, there's like 4 or 5 other alternatives and it seems like I'd be shoehorning myself into a bunch of integration work for tools I might not use.

With that being said, if there was a way to invoke navi where you passed it cheats through stdin or to a specific location, then I could imagine there being a potential for relatively easy "integration".

today there are a fixed set of sauce "targets" (env, function, alias), and I had generally thought it might be nice to unbound that and just generally allow people to specify arbitrary other targets, say "ext.cheat" in this case.

Maybe at that point, if i squint enough I could imagine allowing for some kind of custom "target handler", which I would imagine you might write in bash (or whatever) and wire together with your "ext.cheat" values in such a way that navi could directly consume the output (say, this custom handler exports NAVI_CHEATS or NAVI_PATH, depending on `navi`'s mechanism for customizing its cheat lookup behavior)?

Is any of the above making sense?

**Comment by DanCardin** [comment]
Closing this issue in favor of a more generalized option.

But sidebar, since i'm probably not likely to implement even that feature any time soon necessarily since i have no obvious use for it at the moment and you haven't responded. I'd say ideal/easier scenario would be if navi (or whatever tool) allows itself to be configured by environment variables, then there would be nothing additional `sauce` would need to do to get you the behavior asked for.
